application: game-ladder
version: 1
runtime: python
api_version: 1

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /
  script: game-ladder.py

- url: /[A-Za-z0-9]+[/]?
  script: game-ladder.py

- url: /[A-Za-z0-9]+/user
  script: game-ladder.py

- url: /[A-Za-z0-9]+/resimulate
  script: game-ladder.py
  login: admin

- url: /[A-Za-z0-9]+/.*
  script: game-ladder.py
  login: required

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin